name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 
      with:
        github_access_token: ${{ secrets.WEBSITE_PAT }} 
        angular_dist_build_folder: dist/tomthorogood
